### PR TITLE
package: repository link

### PR DESCRIPTION
**Pull request by LinusU**
This will make a link to github show up on npm which is hugely appreciated.

### CODE REVIEW

**Comment by alexhultman** [comment]
Nice. Thanks.

**Comment by LinusU** [comment]
No problem! Very interesting project btw, your build setup looks very cool, I've been thinking of something similar for `node-canvas`. Distributing source and relying on users to have libraries installed is a pain :)

**Comment by alexhultman** [comment]
Yeah I focus on distributing binaries instead of having the user compile it up. I also ditched node-gyp in favor of a regular Makefile.

**Comment by LinusU** [comment]
Have you looked at [cmake-js](https://github.com/cmake-js/cmake-js)? I've been using it a bit and it's awesome!

Although I usually use a regular `Makefile` when I only need the basics, and it seems like this project only needs the basics at the moment. It's never a good thing to make things complicated :)

**Comment by alexhultman** [comment]
Yeah I'll be sticking to the basics for now.

**Pull request merged**
